version: "3.8"

services:
  mariadb-master:
    container_name: hsa1021-mariadb-master
    image: mariadb:11.2.2
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=hsa1021
      - MYSQL_ROOT_PASSWORD=mysqlmasterpass
    volumes:
      - ./master/config/bin-log.cnf:/etc/mysql/mariadb.conf.d/bin-log.cnf
      - ./master/data:/var/lib/mysql
    restart: "always"
    networks:
      - hsa1021

  mariadb-slave1:
    container_name: hsa1021-mariadb-slave1
    image: mariadb:11.2.2
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=hsa1021
      - MYSQL_ROOT_PASSWORD=mysqlslave1pass
    volumes:
      - ./slave1/config/bin-log.cnf:/etc/mysql/mariadb.conf.d/bin-log.cnf
      - ./slave1/data:/var/lib/mysql
    restart: "always"
    networks:
      - hsa1021
  
  mariadb-slave2:
    container_name: hsa1021-mariadb-slave2
    image: mariadb:11.2.2
    ports:
      - "3309:3306"
    environment:
      - MYSQL_DATABASE=hsa1021
      - MYSQL_ROOT_PASSWORD=mysqlslave2pass
    volumes:
      - ./slave2/config/bin-log.cnf:/etc/mysql/mariadb.conf.d/bin-log.cnf
      - ./slave2/data:/var/lib/mysql
    restart: "no"
    networks:
      - hsa1021

networks:
  hsa1021:
    name: hsa1021